apiVersion: v1
kind: Service
metadata:
  name: combat
  namespace: ebullientworks
  labels:
    app: monster-combat
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: web
    targetPort: web
  selector:
    app: monster-combat
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: combat-deploy
  namespace: ebullientworks
  labels:
    app: monster-combat
spec:
  template:
    metadata:
      labels:
        app: monster-combat
    spec:
      containers:
      - name: combat
        image: ebullient/dnd-monster-combat:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/liveness
            port: 8080
          initialDelaySeconds: 40
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: combat-servicemonitor
  namespace: monitoring
  labels:
    app: monster-combat
spec:
  selector:
    matchLabels:
      app: monster-combat
  endpoints:
  - port: web
    interval: 15s
    path: /actuator/prometheus
